### PR TITLE
 Fix AUTO_INCREMENT for complex PK

### PR DESCRIPTION
**Pull request by loryk**
### Description

In case we are use complex primary keys, one or many of them can be auto incremented fields. So I think need to add AUTO_INCREMENT without check PRIMIRY is simple or complex.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by dhmlau** [comment]
@loryk , thanks for your PR.  Could you please fix the commit linter error? 
```
**************************************************
**
**  Linting commit logs
**
**  2 problems found:
**    631a93a - Merge pull request #1 from loryk/AUTO_INCREMENT_for: First line should be 50 characters or less (saw 63)
**    b5190c7 - Fix AUTO_INCREMENT for complex primary keys: line 3 longer than 72 characters.
**
**************************************************
```

You can fix it by using `git commit --amend` command, see instructions: https://help.github.com/en/articles/changing-a-commit-message.

As a reference, here is our commit message guideline: 
https://loopback.io/doc/en/contrib/git-commit-messages.html

**Comment by loryk** [comment]
Hmm, for first my comment was very short, for second  I do this from GitHub editor, not from git client... I try re-integrate this latter with other commit messages, but ... a bit amazed by such rules))

**Comment by dhmlau** [comment]
@loryk, for the first commit, there's a limit of 72 characters for the subsequent lines. :)  
I'm not familiar with the github editor (primarily using git commands), so I'm not sure how it got prefixed with the previous commit message.  

Since your PR is out of date, I'd suggest you rebase against upstream and fix the commit message along the way.  I can help you with this if you wish.

**Comment by dhmlau** [comment]
In terms of the code changes, could you please add some tests for `AUTO INCREMENT`? Thanks!

**Comment by loryk** [comment]
Seems like `git commit --amend` not helps. I'am cleanup message from description, try to merge/rebase upstream master... But verification still fail.

**Comment by dhmlau** [comment]
@slnode test please

**Pull request closed without merging**
