### PR TITLE
Fix #222 & #223

### LINKED ISSUE #222: `autoupdate` don't update column like `dataType` accordingly after changing it in model.json.
Original discussion see:
https://github.com/strongloop/loopback-connector-mysql/issues/168#issuecomment-265342481

Copied from original bug description:
``` json
   ...
   "maxDiscount": {
      "type": "number",
      "dataType": "decimal",
      "precision": 5,
      "scale": 2,
      "mysql": {
        "columnName": "PART_DISC_MAX",
        "dataType": "DECIMAL",
        "dataPrecision": 5,
        "dataScale": 2
      }
    }
```
In my case the problem happen if i made change at column's `dataType` or some detail of `dataType`, like `precision` or `length` of the column. If the column doesn't exist, the problem also happen. 

but apparently there is a problem if the index of table is being changed too. I need to make some adjustment with this. I know this `index` feature is still premature, but this feature crucial to my current works.

``` json
    "code": {
      "type": "string",
      "required": true,
      "length": 10,
      "index": {
        "unique": true
      },
      "mysql": {
        "columnName": "PART_NO",
        "dataType": "VARCHAR",
        "dataLength": 10
      }
    },
```

### PR DESCRIPTION
**Pull request by hasanlussa**
Fix mysql column name being ignored on dataType change or new column
being added
Fix mysql column name ignored if index changed

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by hasanlussa** [comment]
@jannyHou move to new PR in here. test being added, everything rebased. cool.
sorry, i messed up rebase order on my previous PR

**Comment by jannyHou** [comment]
@slnode test please

**Comment by jannyHou** [comment]
@hasanlussa Cool! I know that sometimes rebase is painful :) Triggered a CI build. waiting for its result.

**Comment by jannyHou** [comment]
@hasanlussa Awesome the pr LGTM 👍 
One nitpick: Can you squash the two commits into one and rename the single commit as:
"Use expected column name when autoupdate" ?
Those two commit details is nice please keep them:
```
Fix mysql column name being ignored on dataType change or new column
being added
Fix mysql column name ignored if index changed
```

git rebase will guide you do things above:
- run `git rebase -i master` 
- use `r`(means reword) for the first commit and `f`(means squash) for the second commit
- then reword your single commit message
- then run `git push -f`


If rebasing still haunts you and you don't mind I squash them for you, then no need to open a new pr :P I can do it on my end.

**Comment by hasanlussa** [comment]
@jannyHou done. Ty for your guidance, much appreciated.

**Comment by jannyHou** [comment]
@slnode test please

**Comment by jannyHou** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by jannyHou** [comment]
@hasanlussa Sorry but another pr checked in we need to rebase again :(
And I find that you commit your change to the forked master branch, which results in I could not rebase code for you, and it's also not the right way to create pr from forked repo :p

Only a few steps to get it work:
- You create a new branch in your forked repo with `git checkout -b fix/column-name-in-discovery`
  ("fix/column-name-in-discovery" is the branch name)
- Push the new branch to your remote forked repo by `git push -u origin fix/column-name-in-discovery`
- Create a new pr from that branch.
- Waiting for CI pass cost some time and sometimes result in rebasing again and again. If you don't mind, follow https://github.com/blog/2247-improving-collaboration-with-forks to give me access to the forked repo, then I can handle rebasing for you. All credits still go to you :)

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
