### PR TITLE
Typo on README

### PR DESCRIPTION
**Pull request by luckylooke**
#### Related issues

- None

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ssh24** [comment]
@luckylooke Could you please sign the CLA https://cla.strongloop.com/agreements/strongloop/loopback-connector-mysql?

**Comment by luckylooke** [comment]
done :)

**Comment by ssh24** [comment]
@luckylooke Please rebase your branch for the CI checks to be all green. Everything else LGTM.

**Comment by ssh24** [comment]
@slnode test please

**Comment by luckylooke** [comment]
@ssh24 please tell me what is the easiest way to rebase it?

**Comment by ssh24** [comment]
@luckylooke To rebase your branch against the `strongloop:master` which the upstream mysql repo where you cloned from, please follow these steps:
1. Set up an upstream remote `git remote add upstream https://github.com/strongloop/loopback-connector-mysql.git`
2. Checkout your master branch `git checkout master`
3. Fetch from the upstream master `git fetch upstream`
4. Rebase your master against the master of **strongloop:mysql** `git rebase upstream/master`
5. Push your local master into your remote master `git push -f origin master`
6. Checkout the branch you were working on `git checkout <my_branch>`
7. Rebase your current branch against your master `git rebase -i origin/master`
8. Push your local branch into your remote branch `git push -f origin <my_branch>`

**Comment by luckylooke** [comment]
I was making the fix via github page.. so I didn't had it locally, I thought there would be easier process to rebase it. But I have done the steps you send me, understanding maybe a half of it.. 😕 so I hope it is done right now 😊

**Comment by luckylooke** [comment]
It didn't helped, Jenkins still needed rebase.. so I reset the patch-1 branch and commit again, hopefully it would be OK now... if not.. please do the fix your selves, it is just a I character typo. Thanks ☺️

**Comment by ssh24** [comment]
@slnode ok to test

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Pull request merged**
