### PR TITLE
Add support for fractional seconds.

### PR DESCRIPTION
**Pull request by joostdebruijn**
### Description
In MySQL 5.6 the support for saving fractional seconds for the DATETIME datatype was added. This pull request will add support for it to the connector.

I'm not sure about the best way to add test coverage for my changes to the current set of tests. If someone can help me with that, I will appreciate that. 😄

Note: MySQL supports a precision up to 6 digits, however this is not supported in JavaScript (it has a maximum of 3 digits). To avoid problems, I capped the maximum precision for the Date-datatype to three. If you agree with this limitation, I will add something in the README about that.

#### Related issues
#183 

### Checklist
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by joostdebruijn** [comment]
I just realized the maximum precision of three doesn't matter for the connector when creating and maintaining the DATETIME column, so I removed it. When someone needs such precision for other matters without using JavaScript, it should be possible.

However, we may want to mention in the README that JavaScript is not able to parse a precision with more than three digits. It will cause data / precision loss when modifying such database entries via this connector.

**Comment by joostdebruijn** [comment]
I noticed that in the last few days a lot of discussion about timezones took place. Some of the proposed changes (e.g. #271) will probably have influence on this pull request and the way fractional seconds could be supported for this connector.

My suggestion is to set this PR on hold until it is clear which of proposed timezone related changes will be merged in to the master. Then I will update this pull request or create a new one.

**Pull request closed without merging**
