### PR TITLE
fixed setting the value of a non-nullable, non-required field to NULL

### PR DESCRIPTION
**Pull request by mihailignatenko**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
@mihailignatenko thank you for the pull request. Can you please describe what problem/use-case are you trying to solve by this change?

I am not familiar enough with connector projects, I'll leave the review to @raymondfeng .

**Comment by b-admike** [comment]
@mihailignatenko thank you for your contribution. Can you please address @bajtos's questions? Also, please rebase your branch and add unit tests for your changes.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by b-admike** [comment]
@mihailignatenko the code lgtm, but it definitely needs unit tests and a rebase since your branch is out of date.

**Comment by ssh24** [comment]
Closing this PR. Same as #66.

**Pull request closed without merging**
