### PR TITLE
Fix issue #168 autoupdate() ALTER TABLE ignores mysql columnName property in model definition

### PR DESCRIPTION
**Pull request by hasanlussa**
Fix issue #168 autoupdate() ALTER TABLE ignores mysql columnName property in model definition

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by hasanlussa** [comment]
@jannyHou this is the PR for #222 & #223. Can you review it. So much appreciated.

**Comment by jannyHou** [comment]
@hasanlussa Thank you really appreciate your fix, and can you add some test case in https://github.com/strongloop/loopback-connector-mysql/blob/master/test/mysql.autoupdate.test.js to verify your fix?

The CI is failing due to format of commit message, please check our doc about the right format:
https://loopback.io/doc/en/contrib/code-contrib.html#submitting-a-pull-request
Copy the error log here:
```shell
 2 problems found:
**    65af08f - fix mysql column name being ignore when making chan: First line should be 50 characters or less (saw 68)
**    397b37d - fix alter table cannot patch column changes using c: First line should be 50 characters or less (saw 60)
```

**Comment by jannyHou** [comment]
@hasanlussa can you rebase your code with the latest master branch? Thanks :P

**Comment by hasanlussa** [comment]
move to PR #224

**Pull request closed without merging**
