### PR TITLE
Fix expected column name when autoupdate

### PR DESCRIPTION
**Pull request by hasanlussa**
#### Related issues

- #223
- #222

### Checklist
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by hasanlussa** [comment]
@jannyHou my bad, Everything done. collaboration mode allowed. now u can proceed to rebasing the master :sunglasses: . 
Ty

**Comment by jannyHou** [comment]
@slnode test please

**Pull request merged**
