### PR TITLE
Add support for setting default values from the model definition during a migration.

### PR DESCRIPTION
**Pull request by TheRossman**
Hi guys,
I created this pull request in the hopes we could support default values during a migration.

I wanted to add some code to do the same for a DB discovery, but that is more difficult because it also requires a change in loopback-datasource-juggler, so I'm not exactly what to do there.

Hopefully this is of some value, please let me know if there is anything I can do to make it better.

Thanks!

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by TheRossman** [comment]
I've signed the contributor agreement but not sure what that commit linter is complaining about, is it the length of the title of the PR?  sorry  :(

**Comment by TheRossman** [comment]
I've amended the commit message to fix the error with the commit linter.

**Comment by superkhau** [comment]
```
**************************************************
**
**  Linting commit logs
**
**  1 problems found:
**    25e7cea - Add support for setting defaults during a migration: First line should be 50 characters or less (saw 52)
**
**************************************************
```

**Comment by superkhau** [comment]
Can you add some tests to verify your changes and prevent regressions in the future?

**Comment by superkhau** [comment]
@TheRossman Did you manage to code up some tests for this PR?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by TheRossman** [comment]
@superkhau sorry no i've not had time to come back to this.

**Comment by superkhau** [comment]
@TheRossman Should I close this or will you be working on it anytime soon? Say in a couple of weeks?

**Comment by TheRossman** [comment]
@superkhau I'll be honest i'm not going to have time to get back to this, if someone wants to do something useful with it, great, otherwise you can just delete it.

**Comment by superkhau** [comment]
Closing as abandoned. Will reopen is someone wants to take it on in the future. @TheRossman Thanks for the contribution anyways. :+1:

**Pull request closed without merging**
