### PR TITLE
fix and refactoring timestamp and datetime data types handling

### PR DESCRIPTION
**Pull request by darknos**
Fix issue with values like '0000-00-00 00:00:00' and prevent twice converted timezones.

datasource.options.timezone and datasource.options.dateStrings now work correct.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by darknos** [comment]
Quote from MySQL documentation:

> MySQL converts TIMESTAMP values from the current time zone to UTC for storage, and back from UTC to the current time zone for retrieval.

So we don't need to convert to UTC before INSERT and UPDATE.

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by azatoth** [comment]
I've also encountered this issue, and would love to see a resolution soon.

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by loay** [comment]
Hi @darknos 
Can you please rebase to keep it up to date?
Also can you add a unit test so we can catch any future regression?
Thanks

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by loay** [comment]
@slnode test please

**Comment by ssh24** [comment]
@darknos Could you please rebase your branch? There will be some merge conflicts on `lib/migration.js` so please be aware of it.

Could you also please add some unit tests to go with this patch to stop future regressions?

**Comment by darknos** [comment]
I'd prefer to do new pull request from scratch and starting from unit tests. And also dont forget about DATE field type handling.

**Comment by ssh24** [comment]
@darknos Sure, please go ahead and create the new pull request. Please tag me once the PR is up so I can close this one.

**Comment by ssh24** [comment]
@darknos Any update on the status of the new PR?

**Comment by darknos** [comment]
I close it and opened new one #257 written from scratch with unit tests

**Comment by darknos** [comment]
@ssh24 please have a look at #257

**Pull request closed without merging**
