### PR TITLE
fix debug logs  self.debug > debug.enabled

### PR DESCRIPTION
**Pull request by Monstrik**
### Description
fix debug logs  connection is established / connection is failed

- [* ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ssh24** [comment]
@Monstrik Thank you for the contribution. 

- [ ] Could you please sign the CLA? https://cla.strongloop.com/agreements/strongloop/loopback-connector-mysql
- [ ] Could you also please rebase your PR?

**Comment by Monstrik** [comment]
@ssh24 done and ready

**Comment by ssh24** [comment]
@slnode ok to test

**Comment by ssh24** [comment]
@Monstrik Could you rebase the PR please?

**Comment by ssh24** [comment]
@Monstrik To rebase your branch against the `strongloop:master` which the upstream mysql repo where you cloned from, please follow these steps:
1. Set up an upstream remote `git remote add upstream https://github.com/strongloop/loopback-connector-mysql.git`
2. Checkout your master branch `git checkout master`
3. Fetch from the upstream master `git fetch upstream`
4. Rebase your master against the master of **strongloop:mysql** `git rebase upstream/master`
5. Push your local master into your remote master `git push -f origin master`
6. Since you did all your changes on your master, you would **not** need to do the next steps (7,8,9), but if you were to have your changes in a different branch (in a future PR) you would need to continue with steps _7,8,9_
7. Checkout the branch you were working on `git checkout <my_branch>`
8. Rebase your current branch against your master `git rebase -i origin/master`
9. Push your local branch into your remote branch `git push -f origin <my_branch>`

**Comment by Monstrik** [comment]
done

**Comment by ssh24** [comment]
@slnode test please

**Comment by Monstrik** [comment]
and ...

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@Monstrik Could you please give me access to your fork so I can fix the commit linter? https://github.com/blog/2247-improving-collaboration-with-forks

**Comment by ssh24** [comment]
@Monstrik  I suggest not to use your master branch of the fork in the future for contributions as it does a three way merge while rebasing and gives lots of conflicts when landing the PR itself. 

Could you move your changes, only the ones related to `self.debug` into a new branch and do a new PR? Remove your old fork and create a new one and then create a new branch and put your changes in there. 

Once you are done, you can create a new PR for it. But this PR cannot be landed because of the three way merging conflicts and needs to be closed.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
