### PR TITLE
The use of async.each in migration leads to non-deterministic errors with Foreign Key constraints

### PR DESCRIPTION
**Pull request by DaGaMs**
### Description
The problem is that FK constraints require a certain table to exist, otherwise the SQL will fail.
I switched from `each` to `eachSeries` so that at least, I can influence the order in wich tables
are processed manually in my migration boot script.

A better solution would be to first finish creating tables, then deal with foreign keys separately.
This would also fix the issue of circular references (TableA -> Table B, TableB -> TableA).

#### Related issues

- None

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ssh24** [comment]
@DaGaMs Couple of things:
- Please sign the CLA: https://cla.strongloop.com/agreements/strongloop/loopback-connector-mysql
- Undo the change on `package.json`. We **DO NOT** want loopback-connector pointing to your own connector version.
- Fix the commit message. Rules for commit messages:
  - The first line should be less than _50_ characters
  - The second line should be empty
  - Every subsequent line after should be less than _72_ characters

**Comment by DaGaMs** [comment]
Look, it's not my job to fix bugs in LoopBack, so cut me a bit of slack, ok? I seriously have no time for your "add an empty line in your commit message".

I suggest you reject my pull request and just make the changes yourself. It really couldn't be more trivial. replace `async.each` with `async.eachSeries` in migrate.js. Or keep going with a bug in your SDK. Your choice.

**Comment by DaGaMs** [comment]
And as a side-note: I suggest you review your attitude towards 3rd party contributors. Language matters. Next time, try: *"Thanks for your contribution"* for a start, and then maybe a *"could you maybe remove the reference to your own repo from package.json"*. In any case **DO NOT** talk to people who waste their spare time fixing bugs in bold all caps.

**Comment by ssh24** [comment]
Excuse me? I was very polite to you to begin with. I simply requested small changes on your pull request and you made quiet a big deal about it.

Talking like this is not a sign of any good attitude:
> Look, it's not my job to fix bugs in LoopBack, so cut me a bit of slack, ok? I seriously have no time for your "add an empty line in your commit message".

**Comment by DaGaMs** [comment]
You thought it was polite, I perceived it as rather rude, and I gave you a clear explanation why. The point is: we 3rd part contributors do free work for you. So it's not you who gets to define what's polite. If I feel that it was rude, that's what matters. You can either learn from that, or not. In which case you will not have a lot of contributions. See how that works out.

**Comment by ssh24** [comment]
We value your contribution and I apologize if you perceived my comment rude. I will reopen the PR and would like to proceed with it. Could you give me access to your fork so I can fix the problems myself? More on how to give access to your fork on [here](https://github.com/blog/2247-improving-collaboration-with-forks)

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by DaGaMs** [comment]
There doesn't seem to be a way to retrospectively change a PR to allow editing by maintainers. I've made a new PR #262 instead

**Pull request closed without merging**
