### PR TITLE
Prevent filter input array of numbers from getting modified to array of strings

### PR DESCRIPTION
**Pull request by hotaru355**
Fix for issue #82/#93, but with signed CLA

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
@hotaru355 thank you for the pull request. please add a unit-test that fails before your fix and passes once the fix is applied. This will prevent the bug from resurfacing again in the future.

I'll leave the review of the implementation to @raymondfeng, he is more familiar with this project.

**Comment by ulion** [comment]
So this issue still not resolved?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by ulion** [comment]
well, it seems some bigger upgrade removed the related code here, no idea
whether the Sql Connector did the work correctly.

2015-06-11 21:34 GMT+08:00 slnode <notifications@github.com>:

> Can one of the admins verify this patch? To accept patch and trigger a
> build add comment ".*ok\W+to\W+test.*"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/loopback-connector-mysql/pull/94#issuecomment-111137186>
> .
>



-- 
Ulion

**Comment by b-admike** [comment]
This issue that this PR is looking to fix #93 is not present anymore. @hotaru355 are the changes still necessary? Please rebase with master and check. If the changes are still applicable, please add unit tests for your changes.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by b-admike** [comment]
Closing per https://github.com/strongloop/loopback-connector-mysql/issues/93#issuecomment-290817336

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
