### PR TITLE
Fixed bug: Wrong values in mysql after saving buffer fields

### PR DESCRIPTION
**Pull request by mclaud53**
Hi!
I found a bug.
I has BINARY field in mysql.
I declare field in loopback model:
"myField": {
    "type": "buffer"
}
And try to add record.
Instead of hex data in field I see '{"type":"Buffer"...'
There is fix.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by raymondfeng** [comment]
@mclaud53 Thank you for the patch. Can you add a test case?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by eslynunez** [comment]
Hey yall, This looks to still be an issue in 2.4.0. What is the status of this/ is there anything I can do?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by 0candy** [comment]
@eslynunez If you can help add a test case to verify the change. It also requires a rebase and the commit message is too long (Should be max 50 characters). Thanks.

**Comment by ssh24** [comment]
Closing this, similar PR: https://github.com/strongloop/loopback-connector-mysql/pull/227

**Pull request closed without merging**
