### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by monsty**
### Description

Update README.md

#### Related issues

- None

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by dhmlau** [comment]
@monsty , could you please sign the CLA? 
Here is the right URL: https://cla.strongloop.com/agreements/strongloop/loopback-connector-mysql

**Comment by dhmlau** [comment]
@slnode  test please

**Comment by dhmlau** [comment]
Thanks @monsty for your contribution.  Your PR has been landed.

**Pull request merged**
