### PR TITLE
Follow mysql recommendations for handling booleans

### PR DESCRIPTION
**Pull request by superkhau**
Per http://dev.mysql.com/doc/refman/5.7/en/numeric-type-overview.html
`BOOL` and `BOOLEAN` is alias for `TINYINT(1)` thus we should make
sure discover can handle as such.

Introducing three flags:

* treatCHAR1AsString
  default false - treats CHAR(1) as a String instead of a Boolean
* treatBIT1AsBit
  default true - treats BIT(1) as a Boolean instead of a Binary
* treatTINYINT1AsTinyInt
  default true - treats TINYINT(1) as a Boolean instead of a Number

The default handling for CHAR(1) is legacy backward compability due to
custom to use a CHAR(1) to store 'Y', 'N', '0', '1', etc...

Helping land https://github.com/strongloop/loopback-connector-mysql/pull/202

### CODE REVIEW

**Comment by superkhau** [comment]
@azatoth I helped you land the PR here. Thanks for the contribution! :bowing_man:

**Comment by superkhau** [comment]
@Amir-61 @crandmck Can you help with the documentation for this PR? This is a reminder for https://github.com/strongloop/loopback-connector-mysql/pulls#issuecomment-254972372.

**Comment by Amir-61** [comment]
>@Amir-61 @crandmck Can you help with the documentation for this PR? This is a reminder for https://github.com/strongloop/loopback-connector-mysql/pulls#issuecomment-254972372.

This repo is now owned by @strongloop/sq-lb-apex; @kjdelisle is the interupt person of that team; @kjdelisle PTAL.

**Comment by jgwinner** [comment]
I just ran into this hard. The docs DO state that, but 'buffer' is still mapped.

**Comment by jgwinner** [comment]
Whoa, why did I unassign @kjdelisle ?
I'm not even sure how to do that. Did a Bot do that based on my update?

Who's got this for action?:

**Pull request merged**
