### PR TITLE
Column default zero fix

### PR DESCRIPTION
**Pull request by notbrain**
### Description
Initial fix for column defaults when default value is 0. This enables the use of model.json files with a `mysql` property with default value of 0:

    "mysql": {
      "default": 0
    }

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by notbrain** [comment]
Sorry for the spam, this was premature, but still a bug. Need time to create a test case.

**Pull request closed without merging**
