### PR TITLE
Allow updating the instance property value w/array of nested objects

### PR DESCRIPTION
**Pull request by krv783**
When updating a model instance, which contains a property containing an array of nested Objects, and when using PUT /Model and including the instance id in the request payload, the value of the property containing the array of nested Objects is updated in the MySQL column as [object Object], instead of a string representation of the array of Objects.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by raymondfeng** [comment]
It should be merged with https://github.com/strongloop/loopback-connector-mysql/pull/75

**Comment by raymondfeng** [comment]
I don't see the main change now.

**Comment by raymondfeng** [comment]
You can make multiple commits to the same repo/branch you have and create one PR out of it.

**Comment by krv783** [comment]
@raymondfeng Are we good for now?

**Comment by raymondfeng** [comment]
No, I'm only seeing one file change, which is the test case. Where is the main change?

**Comment by krv783** [comment]
The original change was at : https://github.com/strongloop/loopback-datasource-juggler/pull/454

**Comment by raymondfeng** [comment]
I see.

**Comment by raymondfeng** [comment]
ok to test

**Comment by krv783** [comment]
I had closed the other test file change (lib/mysql.test.js). In my original change for the data-juggler you commented to add a test case in this mysql test file (Blob/?/?/?/mysql.test.js)

**Comment by krv783** [comment]
@raymondfeng So what exactly does the Failed Checks mean? That the existing code failed the test? or that the test failed after implementing my suggested change (in data-source-juggler)?

**Comment by raymondfeng** [comment]
I'm investigating. It could be caused by other commits outside of your PRs.

**Comment by raymondfeng** [comment]
ok to test

**Comment by jannyHou** [comment]
@krv783 any update of this pr? Related pr in juggler and please check comment: https://github.com/strongloop/loopback-datasource-juggler/pull/454#issuecomment-289570166 Thanks.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by jannyHou** [comment]
Close with pr in juggler https://github.com/strongloop/loopback-datasource-juggler/pull/454#issuecomment-289570166

>Seems it's fixed in https://github.com/strongloop/loopback/issues/2123
Thank you so much for contribution, while unfortunately I think this PR is out of date and same fix is already checked. I am closing it now, feel free to reopen it if there is an update, thanks for understanding.

**Pull request closed without merging**
