### PR TITLE
lazyConnect fix

### PR DESCRIPTION
**Pull request by akki-ng**
It will fix this issue. #345 
I'm not sure if this is the only place where we need to correct it, so opening a PR for discussion.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by akki-ng** [comment]
@jannyHou Sure, I'll give you a scenario where ```lazy_connect``` is helpful. In my ```datasources.js```, I've defined ```memory, transient,  mongodb, mysql, email, mgage, google maps, storage-component1, storage-component2, onesignal```

As you can see I've lots of datasources defined. And I'm able to run things perfectly using `node .`
As soon as I go for cluster mode or with any standard ```process-manager```, MYSQL throws an error ```"Connection closed by server"```

After delving deep inside ```loopback-boot```, I realised that datasources are being initialised instantly in a for-loop without using ```async-map```. So as we go with cluster all cluster instances are jamming mysql. And another problem is mysql protocol

1. Handshake
2. Send Authentication Data <within some time window after handshake>
2. Connected <Use connection within some time window else idle/killed>

In this scenario, node js typically being single threaded is not giving cpu juice to ```mysqljs/mysql``` in time, which throws an error based on mysql protocol ```connection closed by server```

I will definitely not want to use insanely huge values for ```connectTimout, accquireTimeout```.

Another problem is, if I want to boot my app faster with these many datasources, it takes significant amount of time, So using ```lazy_connect``` I'm delaying initialization of each datasource until it is required, for which ```loopback-connector-mysql``` threw an error. This PR is to initialise ```loopback-connector-mysql```when it is required, making application boot up faster.

If you find it as a good reason let me know I'll clean up the code. Current PR needs to be cleaned up, was waiting to know if this is the only piece which needs to be patched.

**Comment by akki-ng** [comment]
@jannyHou Any update on this?

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@akki-ng , thanks for pinging. 

The error is:
```
Error: Cannot find module 'loopback-datasource-juggler/test/common.batch.js'
```
@rmg , we have a similar issue with the mongodb connector.  You've helped us resolved.  Could you please help?  Thanks.
> the problem is the `loopback-datasource-juggler` package being installed doesn't actually have those files
> the version published to ci.strongloop.com

**Comment by rmg** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@slnode test please
give it one more try. CI on node 8 passes now, but not node 6.

**Comment by jannyHou** [comment]
@akki-ng Sorry for late reply I was away on another project last month and just back for loopback, if you want to delay the connection until a query sends to the datasource, you can try set `lazyConnect` to true in datasource settings, and then in your bootscript, reset them to false. Because the bootscript is executed after datasource booting phase.

Or the mysql error happens after you do something like above to skip the connection when booting datasource and re-enabled it afterwards? 

You can fork https://github.com/strongloop/loopback-sandbox to give us an app reproduce the error. That would get us on the same page faster then describing it in words. Thanks!

**Comment by akki-ng** [comment]
@jannyHou I did set ```lazyConnect``` to true in datasources setting. I was not planning to hack the system by using bootscripts. Even if using bootscripts in the mentioned fashion will not solve the issue, as the ```client``` would not have been initialised. We must handle below conditions in our code base.
1. Lets not assume ```client``` would have been initialised
2. If ```client``` was not initialised and ```lazyConnect``` is set, then manually create a new ```client```
3. if ```client``` was not initialised and ```lazyConnect``` was false , then we must throw an error regarding ```client initialisation failure```.
Let me know your thoughts. Thanks.

**Comment by dhmlau** [comment]
@jannyHou , could you please follow up? thanks!

**Comment by akki-ng** [comment]
@dhmlau @jannyHou Any update on this?

**Pull request closed without merging**
