### PR TITLE
Fix CI Failures

### PR DESCRIPTION
**Pull request by loay**
connect to https://github.com/strongloop/loopback-connector-mysql/issues/196

### CODE REVIEW

**Comment by loay** [comment]
@slnode test please

**Comment by loay** [comment]
@slnode test please

**Comment by loay** [comment]
test please

**Comment by loay** [comment]
@strongloop/fa-db-connectors PTAL

**Comment by superkhau** [comment]
test please

**Comment by superkhau** [comment]
@loay Please look into the CI failures, seems odd that we have 64 failures. I'd only expect 1/2 unrelated failures at most since it was mostly green before.

**Pull request merged**
