### PR TITLE
[loopback-2.x] Fix CI

### PR DESCRIPTION
**Pull request by dhmlau**
### Description
Fix CI so that CI in juggler `2.x` branch can pass.
Backporting the changes from this PR: https://github.com/strongloop/loopback-connector-mysql/pull/228

#### Related issues
connect to: https://github.com/strongloop/loopback-datasource-juggler/pull/1342

### CODE REVIEW

**Comment by dhmlau** [comment]
@slnode  test please

**Comment by jannyHou** [comment]
@dhmlau any reason why we skip this test case https://github.com/strongloop/loopback-connector-mysql/pull/228/files#diff-ac37332caef3e954ab7f91d6fb6af2f3R408 when backport?
Other than this LGTM.

**Comment by dhmlau** [comment]
I'm backporting what's on the master and 2.x branch. 
https://github.com/strongloop/loopback-connector-mysql/blob/2.x/test/migration.test.js#L388

@loay , i think you might have a better answer.

**Comment by dhmlau** [comment]
@jannyHou  the missing test cases are added.  thanks!

**Pull request merged**
